callbacka/capstone

.travis.yml, client/components/navbar.js, package-lock.json, package.json, public/index.html
=> fix: boilermaker to codewords

.travis.yml, client/components/navbar.js, package-lock.json, package.json, public/index.html
=> game logic

.travis.yml, client/components/navbar.js, package-lock.json, package.json, public/index.html
=> Revert "game logic"

client/components/Board.js, client/components/Table.js, public/index.html, public/style.css, server/classes/deck.js, server/socket/index.js
=> style: board

client/components/Hand.js, server/classes/deck.js, server/socket/index.js
=> Guesserlogic

client/components/Board.js, client/components/Hand.js, client/components/Square.js, client/components/Table.js, server/socket/index.js
=> Clickability

client/components/Hand.js, client/components/HowToPlay.js, client/components/Sidebar.js, client/routes.js, package-lock.json, package.json, public/style.css
How to play component with rules of game and UI explanation of sidebar component. 
---
_#33_
=> feat: how to play page of rules and UI explanation 

server/classes/deck.js
chore: cleaning up deck.js file comments #13
---
_#13_
=> chore: cleaning up deck file comments #13

public/index.html, public/style.css, server/classes/deck.js
=> added modal

client/app.js, client/components/BoardInfo.js, client/components/Hand.js, client/components/Table.js, client/components/TeamInfo.js, client/components/UserInfo.js, public/style.css
=> Playerinfo

client/components/Chat/Chat.js, client/components/Sidebar.js, public/style.css
=> Chatscroll

client/components/Hand.js, package-lock.json, package.json, public/index.html, public/style.css
=> updated modal

client/components/Board.js, client/components/Sidebar.js, client/components/Table.js, server/socket/checkWinner.js, server/socket/index.js
Onclick of assassin card game is over
_#36_
=> Feat: End win conditions for assassin card

client/components/Board.js, client/routes.js, server/index.js
=> fix: auth conflict

public/index.html
=> fix: create modal

server/socket/checkWinner.js
=> fixed typo

public/materialize.min.css, public/style.css
=> css changes to modal

public/style.css
=> minor css updates

client/components/Chat/Chat.js, client/components/Hand.js, client/components/Sidebar.js, server/socket/index.js
=> no more crazy componentdidupdate

client/components/Hand.js, client/components/Sidebar.js, public/index.html, public/style.css
=> fix: sidebar and modal format

client/app.js, client/socket.js
=> fix enpoint

client/components/Square.js, public/materialize.min.css, public/style.css
=> made font larger

client/components/Hand.js
bolded the clue and number given
=> updated player and codemaster view

client/components/Board.js, client/routes.js
=> feat: play again

client/components/Square.js, public/style.css
=> updated font size

public/style.css
=> codemaster borders

client/components/Hand.js, public/style.css
=> Blankinput

client/components/Hand.js, client/components/Square.js
Feat: sound will play on player turn and choose card
_#75_
=> Feat: sound will play on player turn and choose card

client/components/Hand.js, client/components/Sidebar.js, server/socket/index.js
=> changed sidebar things

client/app.js, client/components/Hand.js
=> Userinterfaces

client/components/Hand.js, client/components/Sidebar.js, public/index.html, public/style.css
=> style: css of player view #10

client/components/BoardInfo.js, client/components/Sidebar.js, client/components/Table.js, client/components/TeamInfo.js, public/style.css, server/socket/index.js
=> added some game info on right panel

client/components/Hand.js, client/components/Table.js, public/style.css
=> some styling changes
